### ISSUE TITLE
Null error when attaching event handler to HTML element

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#739]
The console is reporting the following error when loading in version 1.7.0.249
```
index.bundle.cfc2127a6488d11d1d91.js:39058 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at initEventHandlers (index.bundle.cfc2127a6488d11d1d91.js:39058:7)
    at HTMLDocument.<anonymous> (index.bundle.cfc2127a6488d11d1d91.js:38815:3)
```
The code construct is similar to this:
```
  document.getElementById('save-as-board-btn1')
      .addEventListener('click', () => {
      [ . . . ]
    }
```

**Comment by zfi** [comment]
Fixed in v1.7.0.249.
